name: Harmony
favicon: null
layout_spectrum: 0.93136
typography_spectrum: 0.64061
title: ' Creating Harmony'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1eaf1'
    - '#050507'
    - '#8fb4bc'
    - '#4e8689'
    - '#2e2d29'
  brandStrength: 0.5
  lightness: 0.9780944334343076
  saturation: 0.6580368916038424
  rhythmicContrast: 0.5513593717478216
purpose: []
