name: Harmony
favicon: null
layout_spectrum: 0.29551697126589715
typography_spectrum: 0.2582652815617621
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.17610690044239163
  lightness: 0.9780944334343076
  saturation: 0.6580368916038424
  rhythmicContrast: 0.5513593717478216
purpose: []
